general:
  api_key: super-secret-token
  host: 0.0.0.0
  port: 52693
  sample_rate: 16000
models:
  - id: distil-medium-en
    model: distil-medium.en
    batch_size: 12
  - id: turbo-en
    model: large-v3
    quantization: 8bit
    batch_size: 4
  - id: distil-large-v3
    model: distil-large-v3
    batch_size: 8
